### ISSUE TITLE
Scripts Laoding Bug

### ISSUE THREAD

**Issue by Go3shom** [Code-Ideas/Dashborad#2]
Hello Guys,

First, I want to thank you for your contribution & efforts to help Arabian folks.
Second, when I opened the dashboard I found that some resources like images(1), CSS(2), and Js(3) scripts didn't load correctly, even when trying to install the project locally; it gives me the error attached in (4)

Hope you fix them sooner and keep it rocks.

![1](https://user-images.githubusercontent.com/16515127/198932293-980d37f1-8693-460e-89de-c1c23df052cb.png)
![2](https://user-images.githubusercontent.com/16515127/198931918-e2730395-6baf-4528-a2ed-0d2b418ef5f1.png)
![3](https://user-images.githubusercontent.com/16515127/198931906-5396d06e-bc8c-4dfc-80d8-38f758a4440a.png)
![4](https://user-images.githubusercontent.com/16515127/198931524-aa43805e-bfdd-47a8-a403-64ddc85a9ca0.png)

**Comment by Code-Ideas** [comment]
Thanks for sharing
It was changed a permission server error and fixed
